#!/usr/bin/python
# -*- coding: utf-8 -*-
import xbmcplugin,xbmcaddon,xbmcgui,os,sys

addon = xbmcaddon.Addon()
addon_path = addon.getAddonInfo('path') #.decode('utf-8')
xbmcplugin.setContent(handle=int(sys.argv[1]), content='songs')

def add_item(url,infolabels,image=''):
    listitem = xbmcgui.ListItem(infolabels['title'])
    listitem.setInfo('audio',infolabels)
    listitem.setProperty('IsPlayable','true')
    listitem.setArt({ 'thumb': image , 'icon' :image })
    xbmcplugin.addDirectoryItem(int(sys.argv[1]),url,listitem)

add_item('https://tuner.m1.fm/80er.mp3',{"title":'80ER'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/90er.mp3',{"title":'90ER'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-dhiphopcharts-128-mp3',{"title":'CHILLOUT'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/chillout.mp3',{"title":'CLUBMIX'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/oldies.mp3',{"title":'OLDIES'},os.path.join(addon_path,'icon.png'))
add_item('https://pool.radiopaloma.de/RP-Partyschlager_rde.mp3',{"title":'PARTYSCHLAGER'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/rock.mp3',{"title":'ROCK'},os.path.join(addon_path,'icon.png'))
add_item('https://pool.radiopaloma.de/RADIOPALOMA_rde.mp3',{"title":'SCHLAGER'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/softpop.mp3',{"title":'SOFT POP'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/hits.mp3',{"title":'THE HITS'},os.path.join(addon_path,'icon.png'))
add_item('https://tuner.m1.fm/charts.mp3',{"title":'TOP OF THE CHARTS'},os.path.join(addon_path,'icon.png'))
add_item('https://icepool.silvacast.com/DEFJAY_rde.mp3',{"title":'URBAN'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-charts-64-aac',{"title":'bigFM CHARTS'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-dance-64-aac',{"title":'bigFM DANCE'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-reggaevibes-64-aac',{"title":'bigFM Dancehall & Reggae Vibez'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-nitroxdeep-64-aac',{"title":'bigFM Deep & Tech House'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-dhiphopcharts-128-mp3',{"title":'bigFM Deutsche Hip-Hop Charts'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-deutschrap-128-mp3',{"title":'bigFM Deutschrap'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-nitroxedm-64-aac',{"title":'bigFM EDM & Progressive'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-groovenight-64-aac',{"title":'bigFM GROOVENIGHT'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-hiphop-64-aac',{"title":'bigFM HIP-HOP'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-latinbeats-64-aac',{"title":'bigFM Latin Beats'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-mashup-64-aac',{"title":'bigFM MASHUP'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-oldschooldeutsch-128-mp3',{"title":'bigFM Oldschool Deutschrap'},os.path.join(addon_path,'icon.png'))
add_item('https://ilr.bigfm.de/bigfm-party-128-mp3',{"title":'bigFM Party'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-rapfeature-128-aac',{"title":'bigFM Rap Feature'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-oldschool-128-mp3',{"title":'bigFM Oldschool Rap & Hip-Hop'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-rnb-128-mp3',{"title":'bigFM RNB'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-sunsetlounge-64-aac',{"title":'bigFM Sunset Lounge'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-turkey-64-aac',{"title":'bigSES'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio1.mp3',{"title":'I LOVE RADIO'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio2.mp3',{"title":'I LOVE 2 DANCE'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio29-aac.mp3',{"title":'I LOVE BASS'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio17-aac.mp3',{"title":'I LOVE CHILLHOP'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio103.mp3',{"title":'I LOVE DANCE FIRST!'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio26-aac.mp3',{"title":'I LOVE DANCE HISTORY'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio6.mp3',{"title":'I LOVE DEUTSCHRAP BESTE'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio104.mp3',{"title":'I LOVE DEUTSCHRAP FIRST!'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio16.mp3',{"title":'I LOVE GREATEST HITS'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio21.mp3',{"title":'I LOVE HARDSTYLE'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio20.mp3',{"title":'I LOVE THE CLUB'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio4.mp3',{"title":'I LOVE THE DJ'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio15.mp3',{"title":'.I LOVE THE SUN'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio9.mp3',{"title":'I LOVE TOP 100 CHARTS'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.ilovemusic.de/iloveradio14.mp3',{"title":'I LOVE PARTY HARD'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream16.radiohost.de/rm-80s_mp3-192',{"title":'80s HITS by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream13.radiohost.de/90s',{"title":'90s HITS by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream14.radiohost.de/rm-best-of-schlager_mp3-192',{"title":'Best of Schlager by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream12.radiohost.de/breakz',{"title":'Bass by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream15.radiohost.de/rm-deutsche-hits_mp3-192',{"title":'Deutsche Hits by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream15.radiohost.de/techhouse',{"title":'Techhouse by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream15.radiohost.de/top40',{"title":'Top40 by Rautemusik'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/festival/mp3-192',{"title":'Sunshine Live - Festival'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/hard/mp3-192',{"title":'Sunshine Live - Hard'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/house/mp3-192',{"title":'Sunshine Live - House'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/mayday/mp3-192',{"title":'Sunshine Live - Mayday'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/natureone/mp3-192',{"title":'Sunshine Live - Nature One'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/timewarp/mp3-192',{"title":'Sunshine Live - Time Warp'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/lounge/mp3-192',{"title":'Sunshine Live - Lounge'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/dnb/mp3-192',{"title":'Sunshine Live - Drum N Bass'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/techno/mp3-192',{"title":'Sunshine Live - Techno'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.sunshine-live.de/trance/mp3-192',{"title":'Sunshine Live - Trance'},os.path.join(addon_path,'icon.png'))
add_item('https://campfm.radionetz.de:8001/campfm.mp3',{"title":'CampFM - Das Festivalradio'},os.path.join(addon_path,'icon.png'))
add_item('https://playerservices.streamtheworld.com/api/livestream-redirect/OWR_INTERNATIONAL.mp3',{"title":'Tomorrowland - One World Radio'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.rsa-sachsen.de/maxis/mp3-192',{"title":'RSA-Maxis-Maximal'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.rsa-sachsen.de/disco/mp3-192',{"title":'RSA-Disco'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.rsa-sachsen.de/rsa-oldies/mp3-192',{"title":'RSA-Oldies'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.rsa-sachsen.de/rsa-rockzirkus/mp3-192',{"title":'RSA-Rockzirkus'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.laut.fm/top100germany',{"title":'Top 100 Germany'},os.path.join(addon_path,'icon.png'))
add_item('https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3',{"title":'1Live'},os.path.join(addon_path,'icon.png'))
add_item('http://mp3.radioguetersloh.c.nmdn.net/radioguetersloh/livestream.mp3',{"title":'Radio Guetersloh'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream04-cluster01.radiohost.de/saw-70er_128',{"title":'SAW-70er'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream03-cluster01.radiohost.de/saw-80er_128',{"title":'SAW-80er'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream03-cluster01.radiohost.de/saw-90er_128',{"title":'SAW-90er'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream05-cluster01.radiohost.de/saw-2000er_128',{"title":'SAW-2000er'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream04-cluster01.radiohost.de/saw-deutsch_128',{"title":'SAW-Deutsche Hits'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream07-cluster01.radiohost.de/saw-party_128',{"title":'SAW-Party Hits'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream02-cluster01.radiohost.de/saw-partyschlager_128',{"title":'SAW-Partyschlager'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream04-cluster01.radiohost.de/saw-rock_128',{"title":'SAW-Rock Songs'},os.path.join(addon_path,'icon.png'))
add_item('http://saw-de-hz-fal-stream07-cluster01.radiohost.de/rockland_128',{"title":'SAW-Rockland'},os.path.join(addon_path,'icon.png'))
add_item('http://stream.89.0rtl.de/deutsch-rap/mp3-128',{"title":'RTL-Deutsch Rap'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.90s90s.de/boygroup/mp3-192/streams.90s90s.de/',{"title":'90s90s Radio-Boygroups'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.90s90s.de/eurodance/mp3-192/streams.90s90s.de/',{"title":'90s90s Radio-Dance'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.90s90s.de/pop/mp3-192/streams.90s90s.de/',{"title":'90s90s Radio-Hits'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-deutsch/mp3-192',{"title":'Delta Radio-Deutsch'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/hiphop/mp3-192',{"title":'Delta Radio-Hiphop'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-sommer/mp3-192',{"title":'Delta Radio-Sommer'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-alternative/mp3-192',{"title":'Delta Radio-Alternativ'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-foehnfrisur/mp3-128',{"title":'Delta Radio — Hardrock & heavy Metal (Föhnfrisur)'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-unplugged/mp3-192',{"title":'Delta Radio-Unplugged'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-poprock/mp3-192',{"title":'Delta Radio-Rockpop'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.deltaradio.de/delta-grunge/mp3-192',{"title":'Delta Radio-Grunge'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/germanytop40',{"title":'Energy-German Top 40'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/madeingermany',{"title":'Energy-Made in Germany'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/deutschrap',{"title":'Energy-German Hiphop'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/lounge',{"title":'Energy-Lounge'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/dance',{"title":'Energy-Dance'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/hits',{"title":'Energy-Hits'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/master',{"title":'Energy-Mastermix'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/partyhits',{"title":'Energy-Partyhits'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/reggae',{"title":'Energy-Reggae'},os.path.join(addon_path,'icon.png'))
add_item('http://nrj.de/hitsremix',{"title":'Energy-Hit Remix'},os.path.join(addon_path,'icon.png'))
add_item('https://streams.bigfm.de/bigfm-rockamring-128-mp3',{"title":'Rock am Ring'},os.path.join(addon_path,'icon.png'))
add_item('https://rautemusik-de-hz-fal-stream17.radiohost.de/wackenradio',{"title":'Wacken Radio'},os.path.join(addon_path,'icon.png'))
add_item('https://bob.hoerradar.de/radiobob-wacken-mp3-mq',{"title":'RADIO BOB! BOBs Wacken Nonstop'},os.path.join(addon_path,'icon.png'))
add_item('https://wacken.stream.laut.fm/wacken',{"title":'Wacken'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-classicrock/mp3-192',{"title":'Classic Rock'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-bestofrock/mp3-192',{"title":'Best of Rock'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-rockhits/mp3-192',{"title":'Rockhits'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-metal/mp3-192',{"title":'Metal'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-hardrock/mp3-192',{"title":'Hardrock'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-festival/mp3-192',{"title":'Rock Festival'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-grunge/mp3-192',{"title":'Grunge'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-acdc/mp3-192',{"title":'AC DC'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-queen/mp3-192',{"title":'Queen'},os.path.join(addon_path,'icon.png'))
add_item('http://streams.radiobob.de/bob-kuschelrock/mp3-192',{"title":'Kuschelrock'},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
add_item('',{"title":''},os.path.join(addon_path,'icon.png'))
xbmc.executebuiltin('Container.SetViewMode(100)')
xbmcplugin.endOfDirectory(int(sys.argv[1]))
#Radio Stube Radio